GET http://localhost:8383


###
GET http://localhost:8383/dashboard
###
GET http://localhost:8383/api/data
###
POST http://localhost:8383/api/data
Content-Type: application/json

{
    "name": "Brians"
}

###

DELETE http://localhost:8383/api/data